### ISSUE TITLE
Release requirement.

### ISSUE THREAD

**Issue by RuofengX** [4o4E/Boom#2]
These time, I am looking for a protect plugin running in 1.18.  The result of trendous searching is upsetting, until I found this repo.  
I came from [here](https://www.mcbbs.net/thread-1150139-1-1.html) and I cannot login onto suckbbs, my account was banned becaused of unofficial emberld trade(which is sold by suckbbs official, I think it's not my fault). I googled your name(404E), and finally found here.  
I am not familiar with grandle or maven, and also not good at Java language, so please publish a x86_64 release here, it would help people like me. Otherwise I would fork this project and build another repo with GPL3 license and, most importantly, a RELEASE.

**Comment by 4o4E** [comment]
I'm rewriting this plug-in, but I haven't finished yet. Available versions: 
[https://github.com/4o4E/Boom/releases/tag/1.3.3](https://github.com/4o4E/Boom/releases/tag/1.3.3)
