### ISSUE TITLE
会兼容Folia吗？

### ISSUE THREAD

**Issue by L1bws** [4o4E/Boom#6]
![folia](https://user-images.githubusercontent.com/51532767/232837237-a0f62065-a261-4817-ab7f-6cc5c522d40a.png)

**Comment by 4o4E** [comment]
> ![folia](https://user-images.githubusercontent.com/51532767/232837237-a0f62065-a261-4817-ab7f-6cc5c522d40a.png)

这是paper的分支，理论上是支持的
